language: go

go:
  - "1.16.x"  

services:
  - redis-server

install:
    - go get -v .
    - go get -v golang.org/x/lint/golint
    - go get -v github.com/easierway/concurrent_map

script:
    - diff <(gofmt -d .) <(echo -n)
    - go build ./...
    - go test -v ./...
    - go vet  ./...
    - go build ./...
    