language: go

go:
  - "1.13.x" 

env: 
  
install:
    - go get -v .
    - go get -v golang.org/x/lint/golint

script:
    - diff <(gofmt -d .) <(echo -n)
    - go vet -x ./...
    - golint -set_exit_status ./... 